name: super_reminder
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.7
dependencies:
  cupertino_icons: ^1.0.8
  date_picker_timeline: 1.2.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^20.0.0
  flutter_local_notifications_linux: ^7.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_timezone: ^5.0.1
  fluttertoast: ^9.0.0
  google_fonts: ^8.0.0
  intl: ^0.19.0
  logger: ^2.0.2
  lottie: ^3.3.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
  sqflite: ^2.2.8+4
  timezone: ^0.10.0
  
dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/logo/
    - assets/lottie/
    - assets/data/
  uses-material-design: true
