name: super_reminder
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.7
dependencies:
  cupertino_icons: ^1.0.8
  date_picker_timeline: 1.2.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.0.0
  flutter_local_notifications_linux: ^7.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_timezone: ^5.0.1
  fluttertoast: ^9.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^8.0.0
  intl: ^0.19.0
  introduction_screen: ^4.0.0
  lottie: ^3.3.2
  sqflite: ^2.2.8+4
  timezone: ^0.10.0
  
dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/logo/
    - assets/lottie/
    - assets/data/
  uses-material-design: true
